//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LJV7_DllSampleAll.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LJV7_DllSampleAll.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutoZero.
        /// </summary>
        internal static string SID_AUTO_ZERO {
            get {
                return ResourceManager.GetString("SID_AUTO_ZERO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChangeActiveProgram.
        /// </summary>
        internal static string SID_CHANGE_ACTIVE_PROGRAM {
            get {
                return ResourceManager.GetString("SID_CHANGE_ACTIVE_PROGRAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CheckMemoryAccess.
        /// </summary>
        internal static string SID_CHECK_MEMORY_ACCESS {
            get {
                return ResourceManager.GetString("SID_CHECK_MEMORY_ACCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClearError.
        /// </summary>
        internal static string SID_CLEAR_ERROR {
            get {
                return ResourceManager.GetString("SID_CLEAR_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClearMemory.
        /// </summary>
        internal static string SID_CLEAR_MEMORY {
            get {
                return ResourceManager.GetString("SID_CLEAR_MEMORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CommClose.
        /// </summary>
        internal static string SID_COMM_CLOSE {
            get {
                return ResourceManager.GetString("SID_COMM_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string SID_COMPRESS_X_2 {
            get {
                return ResourceManager.GetString("SID_COMPRESS_X_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        internal static string SID_COMPRESS_X_4 {
            get {
                return ResourceManager.GetString("SID_COMPRESS_X_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OFF.
        /// </summary>
        internal static string SID_COMPRESS_X_OFF {
            get {
                return ResourceManager.GetString("SID_COMPRESS_X_OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EthernetOpen.
        /// </summary>
        internal static string SID_ETHERNET_OPEN {
            get {
                return ResourceManager.GetString("SID_ETHERNET_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finalize.
        /// </summary>
        internal static string SID_FINALIZE {
            get {
                return ResourceManager.GetString("SID_FINALIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetActiveProgram.
        /// </summary>
        internal static string SID_GET_ACTIVE_PROGRAM {
            get {
                return ResourceManager.GetString("SID_GET_ACTIVE_PROGRAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetBatchProfile.
        /// </summary>
        internal static string SID_GET_BATCH_PROFILE {
            get {
                return ResourceManager.GetString("SID_GET_BATCH_PROFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetBatchProfileAdvance.
        /// </summary>
        internal static string SID_GET_BATCH_PROFILE_ADVANCE {
            get {
                return ResourceManager.GetString("SID_GET_BATCH_PROFILE_ADVANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetError.
        /// </summary>
        internal static string SID_GET_ERROR {
            get {
                return ResourceManager.GetString("SID_GET_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetMeasurementValue.
        /// </summary>
        internal static string SID_GET_MEASUREMENT_VALUE {
            get {
                return ResourceManager.GetString("SID_GET_MEASUREMENT_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetProfile.
        /// </summary>
        internal static string SID_GET_PROFILE {
            get {
                return ResourceManager.GetString("SID_GET_PROFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetProfileAdvance.
        /// </summary>
        internal static string SID_GET_PROFILE_ADVANCE {
            get {
                return ResourceManager.GetString("SID_GET_PROFILE_ADVANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetSetting.
        /// </summary>
        internal static string SID_GET_SETTING {
            get {
                return ResourceManager.GetString("SID_GET_SETTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save to the configuration file.
        /// </summary>
        internal static string SID_GET_SETTING_FILE {
            get {
                return ResourceManager.GetString("SID_GET_SETTING_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetStorageBatchProfile.
        /// </summary>
        internal static string SID_GET_STORAGE_BATCH_PROFILE {
            get {
                return ResourceManager.GetString("SID_GET_STORAGE_BATCH_PROFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetStorageData.
        /// </summary>
        internal static string SID_GET_STORAGE_DATA {
            get {
                return ResourceManager.GetString("SID_GET_STORAGE_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetStorageProfile.
        /// </summary>
        internal static string SID_GET_STORAGE_PROFILE {
            get {
                return ResourceManager.GetString("SID_GET_STORAGE_PROFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetStorageStatus.
        /// </summary>
        internal static string SID_GET_STORAGE_STATUS {
            get {
                return ResourceManager.GetString("SID_GET_STORAGE_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetTime.
        /// </summary>
        internal static string SID_GET_TIME {
            get {
                return ResourceManager.GetString("SID_GET_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetVersion.
        /// </summary>
        internal static string SID_GET_VERSION {
            get {
                return ResourceManager.GetString("SID_GET_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HighSpeedData CommunicationFinalize.
        /// </summary>
        internal static string SID_HIGH_SPEED_DATA_COMMUNICATION_FINALIZE {
            get {
                return ResourceManager.GetString("SID_HIGH_SPEED_DATA_COMMUNICATION_FINALIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HighSpeedDataEthernet CommunicationInitalize.
        /// </summary>
        internal static string SID_HIGH_SPEED_DATA_ETHERNET_COMMUNICATION_INITALIZE {
            get {
                return ResourceManager.GetString("SID_HIGH_SPEED_DATA_ETHERNET_COMMUNICATION_INITALIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HighSpeedDataUSB CommunicationInitalize.
        /// </summary>
        internal static string SID_HIGH_SPEED_DATA_USB_COMMUNICATION_INITALIZE {
            get {
                return ResourceManager.GetString("SID_HIGH_SPEED_DATA_USB_COMMUNICATION_INITALIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialize.
        /// </summary>
        internal static string SID_INITIALIZE {
            get {
                return ResourceManager.GetString("SID_INITIALIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InitializeSetting.
        /// </summary>
        internal static string SID_INITIALIZE_SETTING {
            get {
                return ResourceManager.GetString("SID_INITIALIZE_SETTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] : {1}(0x{2:x4}).
        /// </summary>
        internal static string SID_LOG_FORMAT {
            get {
                return ResourceManager.GetString("SID_LOG_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FULL.
        /// </summary>
        internal static string SID_MEASURE_RANGE_FULL {
            get {
                return ResourceManager.GetString("SID_MEASURE_RANGE_FULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIDDLE.
        /// </summary>
        internal static string SID_MEASURE_RANGE_MIDDLE {
            get {
                return ResourceManager.GetString("SID_MEASURE_RANGE_MIDDLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMALL.
        /// </summary>
        internal static string SID_MEASURE_RANGE_SMALL {
            get {
                return ResourceManager.GetString("SID_MEASURE_RANGE_SMALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ＃Undefined RC (0x{0,0:X4}).
        /// </summary>
        internal static string SID_NOT_DEFINE_FROMAT {
            get {
                return ResourceManager.GetString("SID_NOT_DEFINE_FROMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PreStartHighSpeedData Communication.
        /// </summary>
        internal static string SID_PRE_START_HIGH_SPEED_DATA_COMMUNICATION {
            get {
                return ResourceManager.GetString("SID_PRE_START_HIGH_SPEED_DATA_COMMUNICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device not open.
        /// </summary>
        internal static string SID_RC_ERR_NO_DEVICE {
            get {
                return ResourceManager.GetString("SID_RC_ERR_NO_DEVICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No free space.
        /// </summary>
        internal static string SID_RC_ERR_NOMEMORY {
            get {
                return ResourceManager.GetString("SID_RC_ERR_NOMEMORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unimplemented Error.
        /// </summary>
        internal static string SID_RC_ERR_NOTIMPL {
            get {
                return ResourceManager.GetString("SID_RC_ERR_NOTIMPL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to open the device.
        /// </summary>
        internal static string SID_RC_ERR_OPEN_DEVICE {
            get {
                return ResourceManager.GetString("SID_RC_ERR_OPEN_DEVICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter error.
        /// </summary>
        internal static string SID_RC_ERR_PARAMETER {
            get {
                return ResourceManager.GetString("SID_RC_ERR_PARAMETER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response reception error.
        /// </summary>
        internal static string SID_RC_ERR_RECEIVE {
            get {
                return ResourceManager.GetString("SID_RC_ERR_RECEIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command send error.
        /// </summary>
        internal static string SID_RC_ERR_SEND {
            get {
                return ResourceManager.GetString("SID_RC_ERR_SEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time out.
        /// </summary>
        internal static string SID_RC_ERR_TIMEOUT {
            get {
                return ResourceManager.GetString("SID_RC_ERR_TIMEOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undefined error.
        /// </summary>
        internal static string SID_RC_ERR_UNKNOWN {
            get {
                return ResourceManager.GetString("SID_RC_ERR_UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 　　-&gt; {0}.
        /// </summary>
        internal static string SID_RC_FORMAT {
            get {
                return ResourceManager.GetString("SID_RC_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal termination.
        /// </summary>
        internal static string SID_RC_OK {
            get {
                return ResourceManager.GetString("SID_RC_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RebootController.
        /// </summary>
        internal static string SID_REBOOT_CONTROLLER {
            get {
                return ResourceManager.GetString("SID_REBOOT_CONTROLLER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OFF.
        /// </summary>
        internal static string SID_RECEIVED_BINNING_OFF {
            get {
                return ResourceManager.GetString("SID_RECEIVED_BINNING_OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ON.
        /// </summary>
        internal static string SID_RECEIVED_BINNING_ON {
            get {
                return ResourceManager.GetString("SID_RECEIVED_BINNING_ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReflectSetting.
        /// </summary>
        internal static string SID_REFLECT_SETTING {
            get {
                return ResourceManager.GetString("SID_REFLECT_SETTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual storage request.
        /// </summary>
        internal static string SID_REQUEST_STORAGE {
            get {
                return ResourceManager.GetString("SID_REQUEST_STORAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string SID_RESET {
            get {
                return ResourceManager.GetString("SID_RESET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NG.
        /// </summary>
        internal static string SID_RESULT_NG {
            get {
                return ResourceManager.GetString("SID_RESULT_NG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string SID_RESULT_OK {
            get {
                return ResourceManager.GetString("SID_RESULT_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RetrunToFactorySetting.
        /// </summary>
        internal static string SID_RETRUN_TO_FACTORY_SETTING {
            get {
                return ResourceManager.GetString("SID_RETRUN_TO_FACTORY_SETTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RewriteTemporarySetting.
        /// </summary>
        internal static string SID_REWRITE_TEMPORARY_SETTING {
            get {
                return ResourceManager.GetString("SID_REWRITE_TEMPORARY_SETTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetSetting.
        /// </summary>
        internal static string SID_SET_SETTING {
            get {
                return ResourceManager.GetString("SID_SET_SETTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read from the configuration file.
        /// </summary>
        internal static string SID_SET_SETTING_FILE {
            get {
                return ResourceManager.GetString("SID_SET_SETTING_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetTime.
        /// </summary>
        internal static string SID_SET_TIME {
            get {
                return ResourceManager.GetString("SID_SET_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartHighSpeedData Communication.
        /// </summary>
        internal static string SID_START_HIGH_SPEED_DATA_COMMUNICATION {
            get {
                return ResourceManager.GetString("SID_START_HIGH_SPEED_DATA_COMMUNICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartMeasure.
        /// </summary>
        internal static string SID_START_MEASURE {
            get {
                return ResourceManager.GetString("SID_START_MEASURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartStorage.
        /// </summary>
        internal static string SID_START_STORAGE {
            get {
                return ResourceManager.GetString("SID_START_STORAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StopHighSpeedData Communication.
        /// </summary>
        internal static string SID_STOP_HIGH_SPEED_DATA_COMMUNICATION {
            get {
                return ResourceManager.GetString("SID_STOP_HIGH_SPEED_DATA_COMMUNICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StopMeasure.
        /// </summary>
        internal static string SID_STOP_MEASURE {
            get {
                return ResourceManager.GetString("SID_STOP_MEASURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StopStorage.
        /// </summary>
        internal static string SID_STOP_STORAGE {
            get {
                return ResourceManager.GetString("SID_STOP_STORAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timing.
        /// </summary>
        internal static string SID_TIMING {
            get {
                return ResourceManager.GetString("SID_TIMING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigger.
        /// </summary>
        internal static string SID_TRIGGER {
            get {
                return ResourceManager.GetString("SID_TRIGGER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReflectSetting.
        /// </summary>
        internal static string SID_UPDATA_SETTING {
            get {
                return ResourceManager.GetString("SID_UPDATA_SETTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UsbOpen.
        /// </summary>
        internal static string SID_USB_OPEN {
            get {
                return ResourceManager.GetString("SID_USB_OPEN", resourceCulture);
            }
        }
    }
}
