'------------------------------------------------------------------------------
' <auto-generated>
'     このコードはツールによって生成されました。
'     ランタイム バージョン:2.0.50727.5472
'
'     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
'     コードが再生成されるときに損失したりします。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System


'このクラスは StronglyTypedResourceBuilder クラスが ResGen
'または Visual Studio のようなツールを使用して自動生成されました。
'メンバを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
'ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
'''<summary>
'''  ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
Friend Class Resources
    
    Private Shared resourceMan As Global.System.Resources.ResourceManager
    
    Private Shared resourceCulture As Global.System.Globalization.CultureInfo
    
    <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
    Friend Sub New()
        MyBase.New
    End Sub
    
    '''<summary>
    '''  このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
        Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
                Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("LJV7_DllSampleAll.Resources", GetType(Resources).Assembly)
                resourceMan = temp
            End If
            Return resourceMan
        End Get
    End Property
    
    '''<summary>
    '''  厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
    '''  現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
        Get
            Return resourceCulture
        End Get
        Set
            resourceCulture = value
        End Set
    End Property
    
    '''<summary>
    '''  AutoZero に類似しているローカライズされた文字列を検索します。
    '''</summary>
    Friend Shared ReadOnly Property SID_AUTO_ZERO() As String
        Get
            Return ResourceManager.GetString("SID_AUTO_ZERO", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  ChangeActiveProgram に類似しているローカライズされた文字列を検索します。
    '''</summary>
    Friend Shared ReadOnly Property SID_CHANGE_ACTIVE_PROGRAM() As String
        Get
            Return ResourceManager.GetString("SID_CHANGE_ACTIVE_PROGRAM", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  CheckMemoryAccess に類似しているローカライズされた文字列を検索します。
    '''</summary>
    Friend Shared ReadOnly Property SID_CHECK_MEMORY_ACCESS() As String
        Get
            Return ResourceManager.GetString("SID_CHECK_MEMORY_ACCESS", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  ClearError に類似しているローカライズされた文字列を検索します。
    '''</summary>
    Friend Shared ReadOnly Property SID_CLEAR_ERROR() As String
        Get
            Return ResourceManager.GetString("SID_CLEAR_ERROR", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  ClearMemory に類似しているローカライズされた文字列を検索します。
    '''</summary>
    Friend Shared ReadOnly Property SID_CLEAR_MEMORY() As String
        Get
            Return ResourceManager.GetString("SID_CLEAR_MEMORY", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  CommClose に類似しているローカライズされた文字列を検索します。
    '''</summary>
    Friend Shared ReadOnly Property SID_COMM_CLOSE() As String
        Get
            Return ResourceManager.GetString("SID_COMM_CLOSE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  2 に類似しているローカライズされた文字列を検索します。
    '''</summary>
    Friend Shared ReadOnly Property SID_COMPRESS_X_2() As String
        Get
            Return ResourceManager.GetString("SID_COMPRESS_X_2", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  4 に類似しているローカライズされた文字列を検索します。
    '''</summary>
    Friend Shared ReadOnly Property SID_COMPRESS_X_4() As String
        Get
            Return ResourceManager.GetString("SID_COMPRESS_X_4", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  OFF に類似しているローカライズされた文字列を検索します。
    '''</summary>
    Friend Shared ReadOnly Property SID_COMPRESS_X_OFF() As String
        Get
            Return ResourceManager.GetString("SID_COMPRESS_X_OFF", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  EthernetOpen に類似しているローカライズされた文字列を検索します。
    '''</summary>
    Friend Shared ReadOnly Property SID_ETHERNET_OPEN() As String
        Get
            Return ResourceManager.GetString("SID_ETHERNET_OPEN", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Finalize に類似しているローカライズされた文字列を検索します。
    '''</summary>
    Friend Shared ReadOnly Property SID_FINALIZE() As String
        Get
            Return ResourceManager.GetString("SID_FINALIZE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  GetActiveProgram に類似しているローカライズされた文字列を検索します。
    '''</summary>
    Friend Shared ReadOnly Property SID_GET_ACTIVE_PROGRAM() As String
        Get
            Return ResourceManager.GetString("SID_GET_ACTIVE_PROGRAM", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  GetBatchProfile に類似しているローカライズされた文字列を検索します。
    '''</summary>
    Friend Shared ReadOnly Property SID_GET_BATCH_PROFILE() As String
        Get
            Return ResourceManager.GetString("SID_GET_BATCH_PROFILE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  GetBatchProfileAdvance に類似しているローカライズされた文字列を検索します。
    '''</summary>
    Friend Shared ReadOnly Property SID_GET_BATCH_PROFILE_ADVANCE() As String
        Get
            Return ResourceManager.GetString("SID_GET_BATCH_PROFILE_ADVANCE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  GetError に類似しているローカライズされた文字列を検索します。
    '''</summary>
    Friend Shared ReadOnly Property SID_GET_ERROR() As String
        Get
            Return ResourceManager.GetString("SID_GET_ERROR", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  GetMeasurementValue に類似しているローカライズされた文字列を検索します。
    '''</summary>
    Friend Shared ReadOnly Property SID_GET_MEASUREMENT_VALUE() As String
        Get
            Return ResourceManager.GetString("SID_GET_MEASUREMENT_VALUE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  GetProfile に類似しているローカライズされた文字列を検索します。
    '''</summary>
    Friend Shared ReadOnly Property SID_GET_PROFILE() As String
        Get
            Return ResourceManager.GetString("SID_GET_PROFILE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  GetProfileAdvance に類似しているローカライズされた文字列を検索します。
    '''</summary>
    Friend Shared ReadOnly Property SID_GET_PROFILE_ADVANCE() As String
        Get
            Return ResourceManager.GetString("SID_GET_PROFILE_ADVANCE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  GetSetting に類似しているローカライズされた文字列を検索します。
    '''</summary>
    Friend Shared ReadOnly Property SID_GET_SETTING() As String
        Get
            Return ResourceManager.GetString("SID_GET_SETTING", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Save to the configuration file に類似しているローカライズされた文字列を検索します。
    '''</summary>
    Friend Shared ReadOnly Property SID_GET_SETTING_FILE() As String
        Get
            Return ResourceManager.GetString("SID_GET_SETTING_FILE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  GetStorageBatchProfile に類似しているローカライズされた文字列を検索します。
    '''</summary>
    Friend Shared ReadOnly Property SID_GET_STORAGE_BATCH_PROFILE() As String
        Get
            Return ResourceManager.GetString("SID_GET_STORAGE_BATCH_PROFILE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  GetStorageData に類似しているローカライズされた文字列を検索します。
    '''</summary>
    Friend Shared ReadOnly Property SID_GET_STORAGE_DATA() As String
        Get
            Return ResourceManager.GetString("SID_GET_STORAGE_DATA", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  GetStorageProfile に類似しているローカライズされた文字列を検索します。
    '''</summary>
    Friend Shared ReadOnly Property SID_GET_STORAGE_PROFILE() As String
        Get
            Return ResourceManager.GetString("SID_GET_STORAGE_PROFILE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  GetStorageStatus に類似しているローカライズされた文字列を検索します。
    '''</summary>
    Friend Shared ReadOnly Property SID_GET_STORAGE_STATUS() As String
        Get
            Return ResourceManager.GetString("SID_GET_STORAGE_STATUS", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  GetTime に類似しているローカライズされた文字列を検索します。
    '''</summary>
    Friend Shared ReadOnly Property SID_GET_TIME() As String
        Get
            Return ResourceManager.GetString("SID_GET_TIME", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  GetVersion に類似しているローカライズされた文字列を検索します。
    '''</summary>
    Friend Shared ReadOnly Property SID_GET_VERSION() As String
        Get
            Return ResourceManager.GetString("SID_GET_VERSION", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  HighSpeedData CommunicationFinalize に類似しているローカライズされた文字列を検索します。
    '''</summary>
    Friend Shared ReadOnly Property SID_HIGH_SPEED_DATA_COMMUNICATION_FINALIZE() As String
        Get
            Return ResourceManager.GetString("SID_HIGH_SPEED_DATA_COMMUNICATION_FINALIZE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  HighSpeedDataEthernet CommunicationInitalize に類似しているローカライズされた文字列を検索します。
    '''</summary>
    Friend Shared ReadOnly Property SID_HIGH_SPEED_DATA_ETHERNET_COMMUNICATION_INITALIZE() As String
        Get
            Return ResourceManager.GetString("SID_HIGH_SPEED_DATA_ETHERNET_COMMUNICATION_INITALIZE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  HighSpeedDataUSB CommunicationInitalize に類似しているローカライズされた文字列を検索します。
    '''</summary>
    Friend Shared ReadOnly Property SID_HIGH_SPEED_DATA_USB_COMMUNICATION_INITALIZE() As String
        Get
            Return ResourceManager.GetString("SID_HIGH_SPEED_DATA_USB_COMMUNICATION_INITALIZE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Initialize に類似しているローカライズされた文字列を検索します。
    '''</summary>
    Friend Shared ReadOnly Property SID_INITIALIZE() As String
        Get
            Return ResourceManager.GetString("SID_INITIALIZE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  InitializeSetting に類似しているローカライズされた文字列を検索します。
    '''</summary>
    Friend Shared ReadOnly Property SID_INITIALIZE_SETTING() As String
        Get
            Return ResourceManager.GetString("SID_INITIALIZE_SETTING", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  [{0}] : {1}(0x{2:x4}) に類似しているローカライズされた文字列を検索します。
    '''</summary>
    Friend Shared ReadOnly Property SID_LOG_FORMAT() As String
        Get
            Return ResourceManager.GetString("SID_LOG_FORMAT", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  FULL に類似しているローカライズされた文字列を検索します。
    '''</summary>
    Friend Shared ReadOnly Property SID_MEASURE_RANGE_FULL() As String
        Get
            Return ResourceManager.GetString("SID_MEASURE_RANGE_FULL", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  MIDDLE に類似しているローカライズされた文字列を検索します。
    '''</summary>
    Friend Shared ReadOnly Property SID_MEASURE_RANGE_MIDDLE() As String
        Get
            Return ResourceManager.GetString("SID_MEASURE_RANGE_MIDDLE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  SMALL に類似しているローカライズされた文字列を検索します。
    '''</summary>
    Friend Shared ReadOnly Property SID_MEASURE_RANGE_SMALL() As String
        Get
            Return ResourceManager.GetString("SID_MEASURE_RANGE_SMALL", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  ＃Undefined RC (0x{0,0:X4}) に類似しているローカライズされた文字列を検索します。
    '''</summary>
    Friend Shared ReadOnly Property SID_NOT_DEFINE_FROMAT() As String
        Get
            Return ResourceManager.GetString("SID_NOT_DEFINE_FROMAT", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  PreStartHighSpeedData Communication に類似しているローカライズされた文字列を検索します。
    '''</summary>
    Friend Shared ReadOnly Property SID_PRE_START_HIGH_SPEED_DATA_COMMUNICATION() As String
        Get
            Return ResourceManager.GetString("SID_PRE_START_HIGH_SPEED_DATA_COMMUNICATION", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Device not open に類似しているローカライズされた文字列を検索します。
    '''</summary>
    Friend Shared ReadOnly Property SID_RC_ERR_NO_DEVICE() As String
        Get
            Return ResourceManager.GetString("SID_RC_ERR_NO_DEVICE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  No free space に類似しているローカライズされた文字列を検索します。
    '''</summary>
    Friend Shared ReadOnly Property SID_RC_ERR_NOMEMORY() As String
        Get
            Return ResourceManager.GetString("SID_RC_ERR_NOMEMORY", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Unimplemented Error に類似しているローカライズされた文字列を検索します。
    '''</summary>
    Friend Shared ReadOnly Property SID_RC_ERR_NOTIMPL() As String
        Get
            Return ResourceManager.GetString("SID_RC_ERR_NOTIMPL", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Failed to open the device に類似しているローカライズされた文字列を検索します。
    '''</summary>
    Friend Shared ReadOnly Property SID_RC_ERR_OPEN_DEVICE() As String
        Get
            Return ResourceManager.GetString("SID_RC_ERR_OPEN_DEVICE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Parameter error に類似しているローカライズされた文字列を検索します。
    '''</summary>
    Friend Shared ReadOnly Property SID_RC_ERR_PARAMETER() As String
        Get
            Return ResourceManager.GetString("SID_RC_ERR_PARAMETER", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Response reception error に類似しているローカライズされた文字列を検索します。
    '''</summary>
    Friend Shared ReadOnly Property SID_RC_ERR_RECEIVE() As String
        Get
            Return ResourceManager.GetString("SID_RC_ERR_RECEIVE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Command send error に類似しているローカライズされた文字列を検索します。
    '''</summary>
    Friend Shared ReadOnly Property SID_RC_ERR_SEND() As String
        Get
            Return ResourceManager.GetString("SID_RC_ERR_SEND", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Time out に類似しているローカライズされた文字列を検索します。
    '''</summary>
    Friend Shared ReadOnly Property SID_RC_ERR_TIMEOUT() As String
        Get
            Return ResourceManager.GetString("SID_RC_ERR_TIMEOUT", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Undefined error に類似しているローカライズされた文字列を検索します。
    '''</summary>
    Friend Shared ReadOnly Property SID_RC_ERR_UNKNOWN() As String
        Get
            Return ResourceManager.GetString("SID_RC_ERR_UNKNOWN", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  　　-&gt; {0} に類似しているローカライズされた文字列を検索します。
    '''</summary>
    Friend Shared ReadOnly Property SID_RC_FORMAT() As String
        Get
            Return ResourceManager.GetString("SID_RC_FORMAT", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Normal termination に類似しているローカライズされた文字列を検索します。
    '''</summary>
    Friend Shared ReadOnly Property SID_RC_OK() As String
        Get
            Return ResourceManager.GetString("SID_RC_OK", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  RebootController に類似しているローカライズされた文字列を検索します。
    '''</summary>
    Friend Shared ReadOnly Property SID_REBOOT_CONTROLLER() As String
        Get
            Return ResourceManager.GetString("SID_REBOOT_CONTROLLER", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  OFF に類似しているローカライズされた文字列を検索します。
    '''</summary>
    Friend Shared ReadOnly Property SID_RECEIVED_BINNING_OFF() As String
        Get
            Return ResourceManager.GetString("SID_RECEIVED_BINNING_OFF", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  ON に類似しているローカライズされた文字列を検索します。
    '''</summary>
    Friend Shared ReadOnly Property SID_RECEIVED_BINNING_ON() As String
        Get
            Return ResourceManager.GetString("SID_RECEIVED_BINNING_ON", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  ReflectSetting に類似しているローカライズされた文字列を検索します。
    '''</summary>
    Friend Shared ReadOnly Property SID_REFLECT_SETTING() As String
        Get
            Return ResourceManager.GetString("SID_REFLECT_SETTING", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Manual storage request に類似しているローカライズされた文字列を検索します。
    '''</summary>
    Friend Shared ReadOnly Property SID_REQUEST_STORAGE() As String
        Get
            Return ResourceManager.GetString("SID_REQUEST_STORAGE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Reset に類似しているローカライズされた文字列を検索します。
    '''</summary>
    Friend Shared ReadOnly Property SID_RESET() As String
        Get
            Return ResourceManager.GetString("SID_RESET", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  NG に類似しているローカライズされた文字列を検索します。
    '''</summary>
    Friend Shared ReadOnly Property SID_RESULT_NG() As String
        Get
            Return ResourceManager.GetString("SID_RESULT_NG", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  OK に類似しているローカライズされた文字列を検索します。
    '''</summary>
    Friend Shared ReadOnly Property SID_RESULT_OK() As String
        Get
            Return ResourceManager.GetString("SID_RESULT_OK", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  RetrunToFactorySetting に類似しているローカライズされた文字列を検索します。
    '''</summary>
    Friend Shared ReadOnly Property SID_RETRUN_TO_FACTORY_SETTING() As String
        Get
            Return ResourceManager.GetString("SID_RETRUN_TO_FACTORY_SETTING", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  RewriteTemporarySetting に類似しているローカライズされた文字列を検索します。
    '''</summary>
    Friend Shared ReadOnly Property SID_REWRITE_TEMPORARY_SETTING() As String
        Get
            Return ResourceManager.GetString("SID_REWRITE_TEMPORARY_SETTING", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  SetSetting に類似しているローカライズされた文字列を検索します。
    '''</summary>
    Friend Shared ReadOnly Property SID_SET_SETTING() As String
        Get
            Return ResourceManager.GetString("SID_SET_SETTING", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Read from the configuration file に類似しているローカライズされた文字列を検索します。
    '''</summary>
    Friend Shared ReadOnly Property SID_SET_SETTING_FILE() As String
        Get
            Return ResourceManager.GetString("SID_SET_SETTING_FILE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  SetTime に類似しているローカライズされた文字列を検索します。
    '''</summary>
    Friend Shared ReadOnly Property SID_SET_TIME() As String
        Get
            Return ResourceManager.GetString("SID_SET_TIME", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  StartHighSpeedData Communication に類似しているローカライズされた文字列を検索します。
    '''</summary>
    Friend Shared ReadOnly Property SID_START_HIGH_SPEED_DATA_COMMUNICATION() As String
        Get
            Return ResourceManager.GetString("SID_START_HIGH_SPEED_DATA_COMMUNICATION", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  StartMeasure に類似しているローカライズされた文字列を検索します。
    '''</summary>
    Friend Shared ReadOnly Property SID_START_MEASURE() As String
        Get
            Return ResourceManager.GetString("SID_START_MEASURE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  StartStorage に類似しているローカライズされた文字列を検索します。
    '''</summary>
    Friend Shared ReadOnly Property SID_START_STORAGE() As String
        Get
            Return ResourceManager.GetString("SID_START_STORAGE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  StopHighSpeedData Communication に類似しているローカライズされた文字列を検索します。
    '''</summary>
    Friend Shared ReadOnly Property SID_STOP_HIGH_SPEED_DATA_COMMUNICATION() As String
        Get
            Return ResourceManager.GetString("SID_STOP_HIGH_SPEED_DATA_COMMUNICATION", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  StopMeasure に類似しているローカライズされた文字列を検索します。
    '''</summary>
    Friend Shared ReadOnly Property SID_STOP_MEASURE() As String
        Get
            Return ResourceManager.GetString("SID_STOP_MEASURE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  StopStorage に類似しているローカライズされた文字列を検索します。
    '''</summary>
    Friend Shared ReadOnly Property SID_STOP_STORAGE() As String
        Get
            Return ResourceManager.GetString("SID_STOP_STORAGE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Timing に類似しているローカライズされた文字列を検索します。
    '''</summary>
    Friend Shared ReadOnly Property SID_TIMING() As String
        Get
            Return ResourceManager.GetString("SID_TIMING", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Trigger に類似しているローカライズされた文字列を検索します。
    '''</summary>
    Friend Shared ReadOnly Property SID_TRIGGER() As String
        Get
            Return ResourceManager.GetString("SID_TRIGGER", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  ReflectSetting に類似しているローカライズされた文字列を検索します。
    '''</summary>
    Friend Shared ReadOnly Property SID_UPDATA_SETTING() As String
        Get
            Return ResourceManager.GetString("SID_UPDATA_SETTING", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  UsbOpen に類似しているローカライズされた文字列を検索します。
    '''</summary>
    Friend Shared ReadOnly Property SID_USB_OPEN() As String
        Get
            Return ResourceManager.GetString("SID_USB_OPEN", resourceCulture)
        End Get
    End Property
End Class
